SWORDS_SHOP = {
    "Iron Sword":     {"price": 500,    "attack": 30,  "description": "یه شمشیر آهنی ساده"},
    "Steel Blade":    {"price": 1500,   "attack": 55,  "description": "شمشیر فولادی"},
    "Wado Ichimonji": {"price": 5000,   "attack": 80,  "description": "شمشیر سفید زورو"},
    "Sandai Kitetsu": {"price": 8000,   "attack": 95,  "description": "شمشیر نفرین‌شده"},
    "Yubashiri":      {"price": 7000,   "attack": 85,  "description": "شمشیر سبک و تیز"},
    "Shusui":         {"price": 15000,  "attack": 110, "description": "شمشیر مشکی افسانه‌ای"},
    "Nidai Kitetsu":  {"price": 20000,  "attack": 125, "description": "نسل دوم کیتتسو"},
    "Enma":           {"price": 35000,  "attack": 150, "description": "شمشیر اودن، فقط قوی‌ها کنترلش می‌کنن"},
    "Yoru":           {"price": 80000,  "attack": 200, "description": "شمشیر سیاه میهاوک"},
    "Ace":            {"price": 70000,  "attack": 190, "description": "شمشیر شنکس"},
    "Murakumogiri":   {"price": 90000,  "attack": 210, "description": "شمشیر وایتبرد"},

    # ===== 🟫 معمولی (Common) — شمشیرهای پایه برای شروع راه =====
    "Old Claw": {"price": 50, "attack": 5, "description": "یه شمشیر ساده برای شروع راه دزدی دریایی"},
    "Old Edge": {"price": 100, "attack": 6, "description": "ارزون ولی قابل اعتماد"},
    "Old Fang": {"price": 150, "attack": 7, "description": "هر دزد دریایی تازه‌کاری یکی از این‌ها داره"},
    "Tin Claw": {"price": 200, "attack": 8, "description": "ساخت محلی، کیفیت معمولی"},
    "Tin Edge": {"price": 250, "attack": 9, "description": "یه شمشیر ساده برای شروع راه دزدی دریایی"},
    "Tin Fang": {"price": 300, "attack": 10, "description": "ارزون ولی قابل اعتماد"},
    "Dull Claw": {"price": 350, "attack": 11, "description": "هر دزد دریایی تازه‌کاری یکی از این‌ها داره"},
    "Dull Edge": {"price": 400, "attack": 12, "description": "ساخت محلی، کیفیت معمولی"},
    "Dull Fang": {"price": 450, "attack": 13, "description": "یه شمشیر ساده برای شروع راه دزدی دریایی"},
    "Iron Claw": {"price": 500, "attack": 14, "description": "ارزون ولی قابل اعتماد"},
    "Iron Edge": {"price": 550, "attack": 15, "description": "هر دزد دریایی تازه‌کاری یکی از این‌ها داره"},
    "Iron Fang": {"price": 600, "attack": 16, "description": "ساخت محلی، کیفیت معمولی"},
    "Old Blade": {"price": 650, "attack": 17, "description": "یه شمشیر ساده برای شروع راه دزدی دریایی"},
    "Old Razor": {"price": 700, "attack": 18, "description": "ارزون ولی قابل اعتماد"},
    "Old Saber": {"price": 750, "attack": 19, "description": "هر دزد دریایی تازه‌کاری یکی از این‌ها داره"},
    "Old Shard": {"price": 800, "attack": 20, "description": "ساخت محلی، کیفیت معمولی"},
    "Old Sword": {"price": 850, "attack": 21, "description": "یه شمشیر ساده برای شروع راه دزدی دریایی"},
    "Old Talon": {"price": 900, "attack": 22, "description": "ارزون ولی قابل اعتماد"},
    "Old Thorn": {"price": 950, "attack": 23, "description": "هر دزد دریایی تازه‌کاری یکی از این‌ها داره"},
    "Tin Blade": {"price": 1000, "attack": 24, "description": "ساخت محلی، کیفیت معمولی"},
    "Tin Razor": {"price": 1050, "attack": 26, "description": "یه شمشیر ساده برای شروع راه دزدی دریایی"},
    "Tin Saber": {"price": 1100, "attack": 27, "description": "ارزون ولی قابل اعتماد"},
    "Tin Shard": {"price": 1150, "attack": 28, "description": "هر دزد دریایی تازه‌کاری یکی از این‌ها داره"},
    "Tin Sword": {"price": 1200, "attack": 29, "description": "ساخت محلی، کیفیت معمولی"},
    "Tin Talon": {"price": 1250, "attack": 30, "description": "یه شمشیر ساده برای شروع راه دزدی دریایی"},
    "Tin Thorn": {"price": 1300, "attack": 31, "description": "ارزون ولی قابل اعتماد"},
    "Worn Claw": {"price": 1350, "attack": 32, "description": "هر دزد دریایی تازه‌کاری یکی از این‌ها داره"},
    "Worn Edge": {"price": 1400, "attack": 33, "description": "ساخت محلی، کیفیت معمولی"},
    "Worn Fang": {"price": 1450, "attack": 34, "description": "یه شمشیر ساده برای شروع راه دزدی دریایی"},
    "Basic Claw": {"price": 1500, "attack": 35, "description": "ارزون ولی قابل اعتماد"},
    "Basic Edge": {"price": 1550, "attack": 36, "description": "هر دزد دریایی تازه‌کاری یکی از این‌ها داره"},
    "Basic Fang": {"price": 1600, "attack": 37, "description": "ساخت محلی، کیفیت معمولی"},
    "Dull Blade": {"price": 1650, "attack": 38, "description": "یه شمشیر ساده برای شروع راه دزدی دریایی"},
    "Dull Razor": {"price": 1700, "attack": 39, "description": "ارزون ولی قابل اعتماد"},
    "Dull Saber": {"price": 1750, "attack": 40, "description": "هر دزد دریایی تازه‌کاری یکی از این‌ها داره"},
    "Dull Shard": {"price": 1800, "attack": 41, "description": "ساخت محلی، کیفیت معمولی"},
    "Dull Sword": {"price": 1850, "attack": 42, "description": "یه شمشیر ساده برای شروع راه دزدی دریایی"},
    "Dull Talon": {"price": 1900, "attack": 43, "description": "ارزون ولی قابل اعتماد"},
    "Dull Thorn": {"price": 1950, "attack": 44, "description": "هر دزد دریایی تازه‌کاری یکی از این‌ها داره"},
    "Iron Blade": {"price": 2000, "attack": 45, "description": "ساخت محلی، کیفیت معمولی"},
    
    # ===== 🟩 کمیاب (Uncommon) =====
    "Gale Claw": {"price": 2200, "attack": 45, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Gale Edge": {"price": 2450, "attack": 46, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Gale Fang": {"price": 2700, "attack": 48, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Tide Claw": {"price": 2950, "attack": 49, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Tide Edge": {"price": 3210, "attack": 50, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Tide Fang": {"price": 3460, "attack": 51, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Wave Claw": {"price": 3710, "attack": 53, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Wave Edge": {"price": 3960, "attack": 54, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Wave Fang": {"price": 4210, "attack": 55, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Coral Claw": {"price": 4460, "attack": 57, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Coral Edge": {"price": 4710, "attack": 58, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Coral Fang": {"price": 4960, "attack": 59, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Gale Blade": {"price": 5220, "attack": 60, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Gale Razor": {"price": 5470, "attack": 62, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Gale Saber": {"price": 5720, "attack": 63, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Gale Shard": {"price": 5970, "attack": 64, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Gale Sword": {"price": 6220, "attack": 66, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Gale Talon": {"price": 6470, "attack": 67, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Gale Thorn": {"price": 6720, "attack": 68, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Honed Claw": {"price": 6970, "attack": 69, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Honed Edge": {"price": 7230, "attack": 71, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Honed Fang": {"price": 7480, "attack": 72, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Naval Claw": {"price": 7730, "attack": 73, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Naval Edge": {"price": 7980, "attack": 74, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Naval Fang": {"price": 8230, "attack": 76, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Sharp Claw": {"price": 8480, "attack": 77, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Sharp Edge": {"price": 8730, "attack": 78, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Sharp Fang": {"price": 8980, "attack": 80, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Tide Blade": {"price": 9240, "attack": 81, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Tide Razor": {"price": 9490, "attack": 82, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Tide Saber": {"price": 9740, "attack": 83, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Tide Shard": {"price": 9990, "attack": 85, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Tide Sword": {"price": 10240, "attack": 86, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Tide Talon": {"price": 10490, "attack": 87, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Tide Thorn": {"price": 10740, "attack": 89, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Wave Blade": {"price": 10990, "attack": 90, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Wave Razor": {"price": 11250, "attack": 91, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},
    "Wave Saber": {"price": 11500, "attack": 92, "description": "ساخته‌شده توسط آهنگرهای ماهر جزیره‌ها"},
    "Wave Shard": {"price": 11750, "attack": 94, "description": "تیغه‌ای تیز و قابل‌اطمینان توی نبرد"},
    "Wave Sword": {"price": 12000, "attack": 95, "description": "یه ارتقای محسوس نسبت به شمشیرهای معمولی"},

    # ===== 🟦 نادر (Rare) =====
    "Ember Claw": {"price": 12500, "attack": 95, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Ember Edge": {"price": 13330, "attack": 97, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Ember Fang": {"price": 14170, "attack": 98, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Frost Claw": {"price": 15000, "attack": 100, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Frost Edge": {"price": 15830, "attack": 102, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Frost Fang": {"price": 16670, "attack": 103, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Royal Claw": {"price": 17500, "attack": 105, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Royal Edge": {"price": 18330, "attack": 107, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Royal Fang": {"price": 19170, "attack": 108, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Storm Claw": {"price": 20000, "attack": 110, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Storm Edge": {"price": 20830, "attack": 112, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Storm Fang": {"price": 21670, "attack": 113, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Cobalt Claw": {"price": 22500, "attack": 115, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Cobalt Edge": {"price": 23330, "attack": 117, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Cobalt Fang": {"price": 24170, "attack": 118, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Cursed Claw": {"price": 25000, "attack": 120, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Cursed Edge": {"price": 25830, "attack": 122, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Cursed Fang": {"price": 26670, "attack": 123, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Ember Blade": {"price": 27500, "attack": 125, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Ember Razor": {"price": 28330, "attack": 127, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Ember Saber": {"price": 29170, "attack": 128, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Ember Shard": {"price": 30000, "attack": 130, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Ember Sword": {"price": 30830, "attack": 132, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Ember Talon": {"price": 31670, "attack": 133, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Ember Thorn": {"price": 32500, "attack": 135, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Frost Blade": {"price": 33330, "attack": 137, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Frost Razor": {"price": 34170, "attack": 138, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Frost Saber": {"price": 35000, "attack": 140, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Frost Shard": {"price": 35830, "attack": 142, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Frost Sword": {"price": 36670, "attack": 143, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Frost Talon": {"price": 37500, "attack": 145, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Frost Thorn": {"price": 38330, "attack": 147, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Royal Blade": {"price": 39170, "attack": 148, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Royal Razor": {"price": 40000, "attack": 150, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Royal Saber": {"price": 40830, "attack": 152, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Royal Shard": {"price": 41670, "attack": 153, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Royal Sword": {"price": 42500, "attack": 155, "description": "شمشیری که شایعات زیادی پشتشه"},
    "Royal Talon": {"price": 43330, "attack": 157, "description": "صاحبان قبلیش جنگاورهای معروفی بودن"},
    "Royal Thorn": {"price": 44170, "attack": 158, "description": "کنترل کاملش به مهارت بالایی نیاز داره"},
    "Shadow Claw": {"price": 45000, "attack": 160, "description": "شمشیری که شایعات زیادی پشتشه"},
    

    
    # ===== 🟪 حماسی (Epic) =====
    "Mythic Claw": {"price": 46000, "attack": 160, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Mythic Edge": {"price": 48670, "attack": 163, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Mythic Fang": {"price": 51330, "attack": 165, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Wraith Claw": {"price": 54000, "attack": 168, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Wraith Edge": {"price": 56670, "attack": 170, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Wraith Fang": {"price": 59330, "attack": 173, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Abyssal Claw": {"price": 62000, "attack": 175, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Abyssal Edge": {"price": 64670, "attack": 178, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Abyssal Fang": {"price": 67330, "attack": 181, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Eclipse Claw": {"price": 70000, "attack": 183, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Eclipse Edge": {"price": 72670, "attack": 186, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Eclipse Fang": {"price": 75330, "attack": 188, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Inferno Claw": {"price": 78000, "attack": 191, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Inferno Edge": {"price": 80670, "attack": 193, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Inferno Fang": {"price": 83330, "attack": 196, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Mythic Blade": {"price": 86000, "attack": 198, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Mythic Razor": {"price": 88670, "attack": 201, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Mythic Saber": {"price": 91330, "attack": 204, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Mythic Shard": {"price": 94000, "attack": 206, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Mythic Sword": {"price": 96670, "attack": 209, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Mythic Talon": {"price": 99330, "attack": 211, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Mythic Thorn": {"price": 102000, "attack": 214, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Tempest Claw": {"price": 104670, "attack": 216, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Tempest Edge": {"price": 107330, "attack": 219, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Tempest Fang": {"price": 110000, "attack": 222, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Volcano Claw": {"price": 112670, "attack": 224, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Volcano Edge": {"price": 115330, "attack": 227, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Volcano Fang": {"price": 118000, "attack": 229, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Wraith Blade": {"price": 120670, "attack": 232, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Wraith Razor": {"price": 123330, "attack": 234, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Wraith Saber": {"price": 126000, "attack": 237, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Wraith Shard": {"price": 128670, "attack": 239, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Wraith Sword": {"price": 131330, "attack": 242, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Wraith Talon": {"price": 134000, "attack": 245, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Wraith Thorn": {"price": 136670, "attack": 247, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Abyssal Blade": {"price": 139330, "attack": 250, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Abyssal Razor": {"price": 142000, "attack": 252, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},
    "Abyssal Saber": {"price": 144670, "attack": 255, "description": "فقط جنگاورهای باتجربه ازش استفاده می‌کنن"},
    "Abyssal Shard": {"price": 147330, "attack": 257, "description": "قدرتش توی میدون نبرد زبانزده"},
    "Abyssal Sword": {"price": 150000, "attack": 260, "description": "یکی از شمشیرهای دست‌ساز مشهور دنیا"},

    # ===== 🟧 افسانه‌ای (Legendary) — فقط برای بازیکن‌های پولدار و قوی =====
    "Doom Claw": {"price": 155000, "attack": 260, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Doom Edge": {"price": 166410, "attack": 264, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Doom Fang": {"price": 177820, "attack": 268, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Void Claw": {"price": 189230, "attack": 272, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Void Edge": {"price": 200640, "attack": 276, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Void Fang": {"price": 212050, "attack": 281, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Chaos Claw": {"price": 223460, "attack": 285, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Chaos Edge": {"price": 234870, "attack": 289, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Chaos Fang": {"price": 246280, "attack": 293, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Demon Claw": {"price": 257690, "attack": 297, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Demon Edge": {"price": 269100, "attack": 301, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Demon Fang": {"price": 280510, "attack": 305, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Doom Blade": {"price": 291920, "attack": 309, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Doom Razor": {"price": 303330, "attack": 313, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Doom Saber": {"price": 314740, "attack": 317, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Doom Shard": {"price": 326150, "attack": 322, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Doom Sword": {"price": 337560, "attack": 326, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Doom Talon": {"price": 348970, "attack": 330, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Doom Thorn": {"price": 360380, "attack": 334, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Hydra Claw": {"price": 371790, "attack": 338, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Hydra Edge": {"price": 383210, "attack": 342, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Hydra Fang": {"price": 394620, "attack": 346, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Void Blade": {"price": 406030, "attack": 350, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Void Razor": {"price": 417440, "attack": 354, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Void Saber": {"price": 428850, "attack": 358, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Void Shard": {"price": 440260, "attack": 363, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Void Sword": {"price": 451670, "attack": 367, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Void Talon": {"price": 463080, "attack": 371, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Void Thorn": {"price": 474490, "attack": 375, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Chaos Blade": {"price": 485900, "attack": 379, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Chaos Razor": {"price": 497310, "attack": 383, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Chaos Saber": {"price": 508720, "attack": 387, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Chaos Shard": {"price": 520130, "attack": 391, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Chaos Sword": {"price": 531540, "attack": 395, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Chaos Talon": {"price": 542950, "attack": 399, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Chaos Thorn": {"price": 554360, "attack": 404, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Cosmic Claw": {"price": 565770, "attack": 408, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
    "Cosmic Edge": {"price": 577180, "attack": 412, "description": "یکی از قدرتمندترین سلاح‌های شناخته‌شده‌ی دنیا"},
    "Cosmic Fang": {"price": 588590, "attack": 416, "description": "اسمش توی تاریخ دزدان دریایی ثبت شده"},
    "Demon Blade": {"price": 600000, "attack": 420, "description": "گفته می‌شه فقط یه نفر توی هر نسل می‌تونه واقعاً کنترلش کنه"},
}
